## 1. BUILD ARGS

ARG SOURCE_IMAGE="silverblue"
ARG SOURCE_SUFFIX="-nvidia"
ARG SOURCE_TAG="41"


### 2. SOURCE IMAGE
FROM ghcr.io/ublue-os/${SOURCE_IMAGE}${SOURCE_SUFFIX}:${SOURCE_TAG}

### 3. AKMods
COPY --from=ghcr.io/ublue-os/akmods:main-41 /rpms/ /tmp/rpms
RUN find /tmp/rpms

### 4. MODIFICATIONS
COPY build.sh /tmp/build.sh
COPY modules /tmp/modules

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    ostree container commit

## NOTES:
# - /var/lib/alternatives is required to prevent failure with some RPM installs
# - All RUN commands must end with ostree container commit
#   see: https://coreos.github.io/rpm-ostree/container/#using-ostree-container-commit
