name: bluebuild
on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here
          - amd-intel.yml
          - nvidia.yml
      
    steps:

      - uses: actions/checkout@v4

      # Setup akmods install for each image based on their kernels
      - name: Set akmods-suffix if amd-intel.yml
        if: matrix.recipe == 'amd-intel.yml'
        run: echo "AKMODS_SUFFIX=main" >> $GITHUB_ENV

      - name: Set akmods-suffix if nvidia.yml
        if: matrix.recipe == 'nvidia.yml'
        run: echo "AKMODS_SUFFIX=nvidia" >> $GITHUB_ENV
      
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Inspect base image and extract its kernel version
        run: |
          LABEL_VALUE=$(skopeo inspect docker://ghcr.io/ublue-os/silverblue-$AKMODS_SUFFIX:latest | jq -r '"\(.Labels["org.opencontainers.image.version"] | split(".")[0])-\(.Labels["ostree.linux"])"')
          echo "Extracted ostree.linux label: $LABEL_VALUE"
          echo "KERNEL_VERSION=$LABEL_VALUE" >> $GITHUB_ENV
        
      - name: Modify akmods.yml with extracted kernel version
        run: |
          sed -i "s/KERNEL_VERSION/${{ env.KERNEL_VERSION }}/g" ./recipes/akmods.yml


      # Build Image
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: false
